### PR TITLE
[ENTESB-11495] Adding DynamoDB QuickStart

### PR DESCRIPTION
**Pull request by Delawen**
Basic DynamoDB Quickstart with images.

### CODE REVIEW

**Comment by Delawen** [comment]
It can be seen here: https://github.com/Delawen/syndesis-quickstarts/tree/master/aws-dynamodb

**Comment by KurtStam** [comment]
Looks great! Can add an export file of your integration and send me a video? I can upload it to our youtube channel.

**Comment by Delawen** [comment]
I will work on the video tomorrow. Any suggestions on what software to use to record? (Last time I used the gtkRecordMyDesktop, not sure if something better came up afterwards)

The zip has credentials... if I remove them or replace them with dummy data will be fine?

**Comment by KurtStam** [comment]
on Mac I simply use QuickTime. Whatever works for you. The zip should only have encrypted secrets, so it should be ok to upload. If they are not encrypted I would say we'd have to open an issue for that and fix it.

**Comment by Delawen** [comment]
The password is encrypted, yes.

**Comment by Delawen** [comment]
Screencast added. I'm not convinced on the quality of the sound. Maybe I should look for a better mic and improve it on a later phase :)

**Comment by KurtStam** [comment]
Video looks good. The only thing missing is the export.

**Comment by Delawen** [comment]
Forgot to mention, but the export is also linked on the README :)

**Pull request merged**
